version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: erp
    ports:
      - "3307:3307"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: ./app
    container_name: app
    ports:
      - "8000:8000"
    # volumes:
    #   - ./app:/var/www/html
    depends_on:
      - mysql

  rest:
    build: ./rest
    container_name: rest
    ports:
      - "5000:5000"
    # volumes:
    #   - ./rest:/app
    depends_on:
      - app

volumes:
  mysql_data:
